// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmrrqplotttjsrepnpfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcnJxcGxvdHR0anNyZXBucGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTQzMzgsImV4cCI6MjA2MzYzMDMzOH0.K21kIwho826Z17BJeuKu3riMEwN-nh8CylvoSxLF94g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);